/**
 * Template planner — the zero-dependency fallback.
 *
 * Produces a VALID deck spec from a prompt using simple heuristics and NO model.
 * It is not "smart" — but it is always available, always produces a deck that
 * passes parseDeck, and lets a reviewer with nothing installed still exercise
 * the full prompt -> deck -> edit -> present loop. It is also the offline test
 * fixture for the rest of the pipeline.
 */

import type { DeckPlanner } from "./types";

const THEME = {
  palette: {
    background: "#10100f",
    surface: "#1c1b19",
    text: "#f5f1e8",
    accent: "#e2703a",
    muted: "#9c968a",
  },
  fontFamily: "'Hanken Grotesk', system-ui, sans-serif",
  baseFontPt: 18,
};

function id(s: string, n: number) {
  return `${s}-${n}`;
}

/** Pull a plausible title from the prompt (first clause, title-cased-ish). */
function deriveTitle(prompt: string): string {
  const firstClause = prompt.split(/[.,;\n]/)[0].trim();
  const words = firstClause.split(/\s+/).slice(0, 8).join(" ");
  return words.charAt(0).toUpperCase() + words.slice(1);
}

/** Heuristic: does this prompt smell like it wants a comparison? */
function wantsComparison(p: string): boolean {
  return /\b(vs|versus|compare|comparison|against)\b/i.test(p);
}

/** Heuristic: does this prompt smell like it has data / numbers / trends? */
function wantsChart(p: string): boolean {
  return /\b(revenue|growth|sales|metrics|trend|quarter|data|chart|number|forecast|kpi)\b/i.test(p);
}

export class TemplatePlanner implements DeckPlanner {
  readonly name = "template";

  async generate(prompt: string): Promise<unknown> {
    const title = deriveTitle(prompt) || "Generated Deck";
    const slides: unknown[] = [];

    // 1) Cover
    slides.push({
      id: "cover",
      layout: "title",
      blocks: [
        {
          id: id("t", 1),
          type: "text",
          role: "title",
          align: "center",
          lines: [{ text: title, level: 0, bullet: false }],
        },
        {
          id: id("t", 2),
          type: "text",
          role: "subtitle",
          align: "center",
          lines: [{ text: "Generated by Slidelang", level: 0, bullet: false }],
        },
      ],
    });

    // 2) Overview bullets pulled from the prompt's clauses.
    const clauses = prompt
      .split(/[.,;\n]/)
      .map((c) => c.trim())
      .filter((c) => c.length > 3)
      .slice(0, 4);
    slides.push({
      id: "overview",
      layout: "title-content",
      blocks: [
        {
          id: "h",
          type: "text",
          role: "title",
          align: "left",
          lines: [{ text: "Overview", level: 0, bullet: false }],
        },
        {
          id: "pts",
          type: "text",
          role: "body",
          align: "left",
          lines: (clauses.length ? clauses : ["Key point one", "Key point two", "Key point three"]).map(
            (c) => ({ text: c, level: 0, bullet: true })
          ),
        },
      ],
    });

    // 3) Optional data slide
    if (wantsChart(prompt)) {
      slides.push({
        id: "data",
        layout: "two-column",
        blocks: [
          {
            id: "h2",
            type: "text",
            role: "title",
            align: "left",
            lines: [{ text: "By the numbers", level: 0, bullet: false }],
          },
          {
            id: "chart",
            type: "chart",
            chartType: "bar",
            title: "Illustrative figures",
            categories: ["Q1", "Q2", "Q3", "Q4"],
            series: [{ name: "Value", values: [2, 3, 4, 5] }],
          },
          {
            id: "note",
            type: "text",
            role: "body",
            align: "left",
            lines: [{ text: "Replace with real figures by editing the spec.", level: 0, bullet: false }],
          },
        ],
      });
    }

    // 4) Optional comparison slide
    if (wantsComparison(prompt)) {
      slides.push({
        id: "compare",
        layout: "two-column",
        blocks: [
          { id: "ch", type: "text", role: "title", align: "left", lines: [{ text: "Comparison", level: 0, bullet: false }] },
          { id: "left", type: "text", role: "body", align: "left", lines: [{ text: "Option A", level: 0, bullet: true }] },
          { id: "right", type: "text", role: "body", align: "left", lines: [{ text: "Option B", level: 0, bullet: true }] },
        ],
      });
    }

    // 5) Closing
    slides.push({
      id: "close",
      layout: "title",
      blocks: [
        { id: "end", type: "text", role: "title", align: "center", lines: [{ text: "Thank you", level: 0, bullet: false }] },
      ],
    });

    return {
      schemaVersion: 1,
      id: "generated",
      title,
      aspectRatio: "16:9",
      theme: THEME,
      slides,
    };
  }
}
